### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by SGR21gtb** [rozniak/ZRev#1]
I want to try it out and to see if it works...

**Comment by rozniak** [comment]
The server implementation is the C# solution under `/srv/ZSrv` if you are a developer and wanting to have a poke with it.

**Comment by SGR21gtb** [comment]
> The server implementation is the C# solution under `/srv/ZSrv` if you are a developer and wanting to have a poke with it.

I'm a consumer though but I can try testing it out as a "dev". Tutorial please

**Comment by rozniak** [comment]
There is nothing meaningful to test, the server is only complete enough to get the clients to the "Looking for players" stage and no further at the moment

**Comment by SGR21gtb** [comment]
> There is nothing meaningful to test, the server is only complete enough to get the clients to the "Looking for players" stage and no further at the moment

Oh :( Thanks.
